### PR TITLE
Fixed warning and bumped stack lts

### PR DESCRIPTION
**Pull request by flip111**

### CODE REVIEW

**Comment by ennocramer** [comment]
Thank you for your contribution!

Unfortunately, I can't merge this PR as is. The `Data.Monoid` import needs to be there for older versions of GHC/base. It could be made conditional, though.

**Comment by flip111** [comment]
Which version of GHC would you like to support ?

**Comment by ennocramer** [comment]
I'm trying to support GHC-8.0.1 and upwards. You can check `.travis.yml` and `.circleci/config.yml` for details.

**Comment by flip111** [comment]
Ok i'm looking into it. By the way builds are also failing because of different reason

```
happy                            > setup: The program 'happy' is required but it could not be found
```

```
--  While building package happy-1.19.5 using:
      /tmp/stack1749/happy-1.19.5/.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0 build --ghc-options ""
    Process exited with code: ExitFailure 1

Exited with code exit status 1
```

https://circleci.com/gh/ennocramer/floskell/937?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by flip111** [comment]
one happy not found error and two out of memory errors

**Comment by ennocramer** [comment]
Awesome! Thank you!

**Pull request merged**
