### PR TITLE
some general code improvements

### PR DESCRIPTION
**Pull request by pacak**

### CODE REVIEW

**Comment by ennocramer** [comment]
I would like to keep `mayM_`, to make it more obvious that there is at most one element. In most places where it is used, the type of the argument is not visible (the argument being bound through some data constructor), so having this information is helpful in understanding the formatting.

**Comment by pacak** [comment]
In most cases name `m...` kind of suggests that it's Maybe but it's up to you to decide. Should I push just polymorphic stuff? Or is it not worth it?

**Comment by ennocramer** [comment]
Please do push your other change individually.  I would like to merge it.

**Comment by ennocramer** [comment]
Thanks a lot!

**Pull request merged**
