### PR TITLE
Loosen aeson bounds

### PR DESCRIPTION
**Pull request by lukel97**

### CODE REVIEW

**Comment by lukel97** [comment]
Tested all passed locally with `cabal test --constraint="aeson^>=1.5"` on ghc-8.10

**Comment by ennocramer** [comment]
Thank you!

**Comment by georgefst** [comment]
Any chance we could get a Hackage release/revision? 

It would resolve a conflict in `haskell-language-server` (which is primarily why @bubba and I care about this).

**Comment by ennocramer** [comment]
Apologies. I wanted to fix another bug before making a new release, but life got in the way. I've released `floskell-0.10.4` now, which includes the relaxed `aeson` bounds.

**Pull request merged**
